ALPHA = %x41-5A / %x61-7A ; Upper- and lower-case ASCII letters (A–Z, a–z)
DIGIT = %x30-39 ; Decimal digits (0–9)
HEXDIG = DIGIT / "A" / "B" / "C" / "D" / "E" / "F" ; Hexadecimal digits (0–9, A–F, a-f)
DQUOTE = %x22 ; Double quotation mark
SP = %x20 ; Space character
HTAB = %x9; ; Horizontal tab
WSP = SP / HTAB ; Whitespace: space or horizontal tab
LWSP = *(WSP / CRLF WSP) ; Linear whitespace (past newline)
VCHAR = %x21-7E ; Visible (printing) character
CHAR = %x01-7F ; Any ASCII character, exluding NUL
OCTET = %x00-FF ; 8 bits of data
CTL = %x00-1F / %x7F ; Controls
CR = %x0D ; Carriage Return
LF = %x0A ; Linefeed
CRLF = CR LF ; Internet-standard newline
BIT = "0" / "1" ; Binary digit